### PR TITLE
Fix incorrect year of blog post

### PR DESCRIPTION
**Pull request by danielnemenyi**
Blog post filename's year was wrong

### CODE REVIEW

**Comment by tecosaur** [comment]
Oh my, that's rather funny. Thanks!

I'm just going to make that change locally and push because it's slightly easier (hope you don't mind not getting credit :sweat_smile: ).

**Comment by tecosaur** [comment]
Ah, and I can also erase any record of my mistake thanks to force-pushing :laughing:

**Comment by ymarco** [comment]
> I'm just going to make that change locally and push because it's slightly easier (hope you don't mind not getting credit sweat_smile ).

FYI you can still give credit when comitting locally with `git commit --author` (`c -A` in Magit)

**Comment by danielnemenyi** [comment]
No problem!

**Pull request closed without merging**
